name: Run unit tests
on:
  workflow_dispatch:
  push:
    branches:
      - main_
    tags:
      - v*
jobs:
  unit-tests-job:
    name: job to run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          clean: 'false'
      - name: Set up Python 3.11
        uses: actions/setup-python@v1
        with:
          python-version: 3.11
          architecture: x64
      - name: Test and coverage
        run: |
          pip install pytest coverage
          make run-test
